services:
  bot-promocao:
    build: .
    container_name: c_bot_promocao
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - ./promo_bot.py:/app/promo_bot.py
      - ./categorias.json:/app/categorias.json
      - ./dados:/app/data

    command: python /app/promo_bot.py